add ripemd-160 and sha512

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -884,6 +884,10 @@ BUILD_SNIFFER_TRUE
 BUILD_SNIFFER_FALSE
 BUILD_AESNI_TRUE
 BUILD_AESNI_FALSE
+BUILD_RIPEMD_TRUE
+BUILD_RIPEMD_FALSE
+BUILD_SHA512_TRUE
+BUILD_SHA512_FALSE
 acx_pthread_config
 PTHREAD_CC
 PTHREAD_LIBS
@@ -1505,7 +1509,10 @@ Optional Features:
   --enable-hugecache      Enable huge session cache (default: disabled)
   --enable-sniffer        Enable CyaSSL sniffer support (default: disabled)
   --enable-aesni          Enable CyaSSL AES-NI support (default: disabled)
+  --enable-ripemd         Enable CyaSSL RIPEMD-160 support (default: disabled)
+  --enable-sha512         Enable CyaSSL SHA-160 support (default: disabled)
   --enable-sessioncerts   Enable session cert storing (default: disabled)
+  --enable-keygen         Enable key generation (default: disabled)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -2418,7 +2425,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=cyassl
- VERSION=1.5.6b
+ VERSION=1.5.7
 
 
 cat >>confdefs.h <<_ACEOF
@@ -4563,7 +4570,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4566 "configure"' > conftest.$ac_ext
+  echo '#line 4573 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7598,11 +7605,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7601: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7608: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7605: \$? = $ac_status" >&5
+   echo "$as_me:7612: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7860,11 +7867,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7863: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7870: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7867: \$? = $ac_status" >&5
+   echo "$as_me:7874: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7922,11 +7929,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7925: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7932: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7929: \$? = $ac_status" >&5
+   echo "$as_me:7936: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10125,7 +10132,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10128 "configure"
+#line 10135 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10223,7 +10230,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10226 "configure"
+#line 10233 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12471,11 +12478,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12474: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12481: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12478: \$? = $ac_status" >&5
+   echo "$as_me:12485: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12533,11 +12540,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12536: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12543: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12540: \$? = $ac_status" >&5
+   echo "$as_me:12547: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13869,7 +13876,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13872 "configure"
+#line 13879 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13967,7 +13974,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13970 "configure"
+#line 13977 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14852,11 +14859,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14855: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14862: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14859: \$? = $ac_status" >&5
+   echo "$as_me:14866: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14914,11 +14921,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14917: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14924: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14921: \$? = $ac_status" >&5
+   echo "$as_me:14928: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17035,11 +17042,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17038: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17045: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17042: \$? = $ac_status" >&5
+   echo "$as_me:17049: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17297,11 +17304,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17300: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17307: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17304: \$? = $ac_status" >&5
+   echo "$as_me:17311: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17359,11 +17366,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17362: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17369: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17366: \$? = $ac_status" >&5
+   echo "$as_me:17373: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19562,7 +19569,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19565 "configure"
+#line 19572 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19660,7 +19667,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19663 "configure"
+#line 19670 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -21767,6 +21774,7 @@ OPTIMIZE_HUGE_CFLAGS="-funroll-loops -DTFM_SMALL_SET"
 DEBUG_CFLAGS="-g -DDEBUG -DDEBUG_CYASSL"
 
 
+# DEBUG
 # Check whether --enable-debug was given.
 if test "${enable_debug+set}" = set; then
   enableval=$enable_debug;  ENABLED_DEBUG=$enableval
@@ -21785,6 +21793,7 @@ else
 fi
 
 
+# SMALL BUILD
 # Check whether --enable-small was given.
 if test "${enable_small+set}" = set; then
   enableval=$enable_small;  ENABLED_SMALL=$enableval
@@ -21803,6 +21812,7 @@ then
 fi
 
 
+# SINGLE THREADED
 # Check whether --enable-singleThreaded was given.
 if test "${enable_singleThreaded+set}" = set; then
   enableval=$enable_singleThreaded;  ENABLED_SINGLETHREADED=$enableval
@@ -21817,6 +21827,7 @@ then
 fi
 
 
+# DTLS
 # Check whether --enable-dtls was given.
 if test "${enable_dtls+set}" = set; then
   enableval=$enable_dtls;  ENABLED_DTLS=$enableval
@@ -21831,6 +21842,7 @@ then
 fi
 
 
+# OPENSSL Extra Compatibility
 # Check whether --enable-opensslExtra was given.
 if test "${enable_opensslExtra+set}" = set; then
   enableval=$enable_opensslExtra;  ENABLED_OPENSSLEXTRA=$enableval
@@ -21845,6 +21857,7 @@ then
 fi
 
 
+# IPv6 Test Apps
 # Check whether --enable-ipv6 was given.
 if test "${enable_ipv6+set}" = set; then
   enableval=$enable_ipv6;  ENABLED_IPV6=$enableval
@@ -21860,6 +21873,7 @@ then
 fi
 
 
+# fastmath
 # Check whether --enable-fastmath was given.
 if test "${enable_fastmath+set}" = set; then
   enableval=$enable_fastmath;  ENABLED_FASTMATH=$enableval
@@ -21875,6 +21889,7 @@ then
 fi
 
 
+# fast HUGE math
 # Check whether --enable-fasthugemath was given.
 if test "${enable_fasthugemath+set}" = set; then
   enableval=$enable_fasthugemath;  ENABLED_FASTHUGEMATH=$enableval
@@ -21891,6 +21906,7 @@ then
 fi
 
 
+# big cache
 # Check whether --enable-bigcache was given.
 if test "${enable_bigcache+set}" = set; then
   enableval=$enable_bigcache;  ENABLED_BIGCACHE=$enableval
@@ -21906,6 +21922,7 @@ then
 fi
 
 
+# HUGE cache
 # Check whether --enable-hugecache was given.
 if test "${enable_hugecache+set}" = set; then
   enableval=$enable_hugecache;  ENABLED_HUGECACHE=$enableval
@@ -21921,6 +21938,7 @@ then
 fi
 
 
+# SNIFFER
 # Check whether --enable-sniffer was given.
 if test "${enable_sniffer+set}" = set; then
   enableval=$enable_sniffer;  ENABLED_SNIFFER=$enableval
@@ -21944,6 +21962,7 @@ else
 fi
 
 
+# AES-NI
 # Check whether --enable-aesni was given.
 if test "${enable_aesni+set}" = set; then
   enableval=$enable_aesni;  ENABLED_AESNI=$enableval
@@ -21972,6 +21991,58 @@ else
 fi
 
 
+
+# RIPEMD
+# Check whether --enable-ripemd was given.
+if test "${enable_ripemd+set}" = set; then
+  enableval=$enable_ripemd;  ENABLED_RIPEMD=$enableval
+else
+   ENABLED_RIPEMD=no
+
+fi
+
+
+if test "$ENABLED_RIPEMD" = "yes"
+then
+    CFLAGS="$CFLAGS -DCYASSL_RIPEMD"
+fi
+
+ if test "x$ENABLED_RIPEMD" = "xyes"; then
+  BUILD_RIPEMD_TRUE=
+  BUILD_RIPEMD_FALSE='#'
+else
+  BUILD_RIPEMD_TRUE='#'
+  BUILD_RIPEMD_FALSE=
+fi
+
+
+
+# SHA512
+# Check whether --enable-sha512 was given.
+if test "${enable_sha512+set}" = set; then
+  enableval=$enable_sha512;  ENABLED_SHA512=$enableval
+else
+   ENABLED_SHA512=no
+
+fi
+
+
+if test "$ENABLED_SHA512" = "yes"
+then
+    CFLAGS="$CFLAGS -DCYASSL_SHA512"
+fi
+
+ if test "x$ENABLED_SHA512" = "xyes"; then
+  BUILD_SHA512_TRUE=
+  BUILD_SHA512_FALSE='#'
+else
+  BUILD_SHA512_TRUE='#'
+  BUILD_SHA512_FALSE=
+fi
+
+
+
+# SESSION CERTS
 # Check whether --enable-sessioncerts was given.
 if test "${enable_sessioncerts+set}" = set; then
   enableval=$enable_sessioncerts;  ENABLED_SESSIONCERTS=$enableval
@@ -21987,6 +22058,23 @@ then
 fi
 
 
+# KEY GENERATION
+# Check whether --enable-keygen was given.
+if test "${enable_keygen+set}" = set; then
+  enableval=$enable_keygen;  ENABLED_KEYGEN=$enableval
+else
+   ENABLED_KEYGEN=no
+
+fi
+
+
+if test "$ENABLED_KEYGEN" = "yes"
+then
+    CFLAGS="$CFLAGS -DCYASSL_KEY_GEN"
+fi
+
+
+# LIBZ
 trylibzdir=""
 
 # Check whether --with-libz was given.
@@ -22116,6 +22204,7 @@ fi
 
 
 
+# OPTIMIZE FLAGS
 if test "$GCC" = "yes"
 then
     if test "$ENABLED_DEBUG" = "no"
@@ -22810,6 +22899,7 @@ fi
 
 
 
+# FINAL
 ac_config_files="$ac_config_files Makefile ctaocrypt/Makefile ctaocrypt/src/Makefile ctaocrypt/test/Makefile ctaocrypt/benchmark/Makefile src/Makefile examples/Makefile examples/client/Makefile examples/server/Makefile examples/echoclient/Makefile examples/echoserver/Makefile testsuite/Makefile sslSniffer/Makefile sslSniffer/sslSnifferTest/Makefile"
 
 cat >confcache <<\_ACEOF
@@ -22947,6 +23037,20 @@ if test -z "${BUILD_AESNI_TRUE}" && test -z "${BUILD_AESNI_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_AESNI\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_AESNI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_RIPEMD_TRUE}" && test -z "${BUILD_RIPEMD_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_RIPEMD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_RIPEMD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_SHA512_TRUE}" && test -z "${BUILD_SHA512_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_SHA512\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_SHA512\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -23653,6 +23757,10 @@ BUILD_SNIFFER_TRUE!$BUILD_SNIFFER_TRUE$ac_delim
 BUILD_SNIFFER_FALSE!$BUILD_SNIFFER_FALSE$ac_delim
 BUILD_AESNI_TRUE!$BUILD_AESNI_TRUE$ac_delim
 BUILD_AESNI_FALSE!$BUILD_AESNI_FALSE$ac_delim
+BUILD_RIPEMD_TRUE!$BUILD_RIPEMD_TRUE$ac_delim
+BUILD_RIPEMD_FALSE!$BUILD_RIPEMD_FALSE$ac_delim
+BUILD_SHA512_TRUE!$BUILD_SHA512_TRUE$ac_delim
+BUILD_SHA512_FALSE!$BUILD_SHA512_FALSE$ac_delim
 acx_pthread_config!$acx_pthread_config$ac_delim
 PTHREAD_CC!$PTHREAD_CC$ac_delim
 PTHREAD_LIBS!$PTHREAD_LIBS$ac_delim
@@ -23661,7 +23769,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 26; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 30; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
